/**
 * The content-completeness report.
 *
 * Prints, for every budget area, how many decisions it has, how many of their
 * alternatives actually carry a sourced figure, and therefore whether that area
 * is a real choice for the person doing the exercise or a placeholder. Also
 * reports whether a surplus, a balanced budget, and a deficit are all reachable.
 *
 * Run with:  npm run report:content
 * Write it:  npm run report:content > CONTENT_REPORT.md
 */
import { DATASET } from '../data'
import { CATEGORIES } from '../data/categories'
import {
  collectSources,
  errorsOnly,
  provenanceSummary,
  validateDataset,
  verificationSummary,
} from '../data/validate'
import { analyzePlayability } from '../engine/playability'
import { choiceBalanceEffect, isScored } from '../engine/budget'
import type { CategoryId } from '../data/types'

const dollars = (n: number): string =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n)

const yesNo = (value: boolean): string => (value ? 'yes' : 'NO')

interface CategoryRow {
  id: CategoryId
  name: string
  decisions: number
  alternatives: number
  scoredAlternatives: number
  areaAppropriation: number | null
  status: 'playable' | 'partial' | 'placeholder'
}

function categoryRows(): CategoryRow[] {
  return CATEGORIES.map((category) => {
    const decisions = DATASET.decisions.filter((d) => d.category === category.id)
    const alternatives = decisions.flatMap((d) => d.choices.filter((c) => !c.isEnactedBaseline))
    const scoredAlternatives = alternatives.filter(
      (c) => isScored(c) && choiceBalanceEffect(c) !== 0,
    )

    // "Playable" means every decision in the area gives the visitor at least one
    // alternative that actually moves the balance. Anything less is called what
    // it is.
    const decisionsWithScored = decisions.filter((d) =>
      d.choices.some((c) => !c.isEnactedBaseline && isScored(c) && choiceBalanceEffect(c) !== 0),
    ).length

    const status: CategoryRow['status'] =
      decisions.length > 0 && decisionsWithScored === decisions.length
        ? 'playable'
        : decisionsWithScored > 0
          ? 'partial'
          : 'placeholder'

    return {
      id: category.id,
      name: category.name,
      decisions: decisions.length,
      alternatives: alternatives.length,
      scoredAlternatives: scoredAlternatives.length,
      areaAppropriation: category.enactedNetAppropriation,
      status,
    }
  })
}

function report(): string {
  const rows = categoryRows()
  const play = analyzePlayability(DATASET)
  const counts = verificationSummary(DATASET)
  const provenance = provenanceSummary(DATASET)
  const errors = errorsOnly(validateDataset(DATASET))
  const sources = collectSources(DATASET)

  const out: string[] = []
  const line = (s = '') => out.push(s)

  line('# Content completeness report')
  line()
  line('Generated by `npm run report:content`. Do not edit by hand.')
  line()
  line(`- **Dataset version:** ${DATASET.version}`)
  line(`- **Fiscal year:** ${DATASET.baseline.fiscalYear}`)
  line(`- **Data verified through:** ${DATASET.baseline.verifiedThrough}`)
  line(`- **Baseline marked provisional:** ${DATASET.baseline.provisional ? 'yes' : 'no'}`)
  line(`- **Validation errors:** ${errors.length}`)
  line(`- **Distinct citations in the dataset:** ${sources.length}`)
  line()

  line('## Can the challenge be played?')
  line()
  line('An exercise in balancing a budget requires that the balance can actually be moved,')
  line('in both directions, by the options on offer.')
  line()
  line('| Check | Result |')
  line('| --- | --- |')
  line(`| Starting balance | ${dollars(play.startingBalance)} |`)
  line(`| Highest reachable balance | ${dollars(play.maxBalance)} |`)
  line(`| Lowest reachable balance | ${dollars(play.minBalance)} |`)
  line(`| A surplus above the enacted balance is reachable | ${yesNo(play.canIncreaseBalance)} |`)
  line(`| A balanced budget is within the reachable range | ${yesNo(play.zeroWithinRange)} |`)
  line(`| A deficit is reachable | ${yesNo(play.canReachDeficit)} |`)
  line(`| Options that move the balance | ${play.scoredAlternatives} |`)
  line(
    `| Decisions offering at least one such option | ${play.decisionsWithScoredAlternatives} of ${DATASET.decisions.length} |`,
  )
  line()

  if (!play.canReachDeficit || !play.canIncreaseBalance) {
    line('> **The challenge is not yet playable end to end.** Until all three outcomes are')
    line('> reachable, the exercise cannot ask a visitor to balance anything, and the deficit')
    line('> warning cannot be triggered from the interface.')
    line()
  }

  line('## By budget area')
  line()
  line('- **playable** — every decision in the area offers an alternative that moves the balance')
  line('- **partial** — some decisions do, some do not')
  line('- **placeholder** — no alternative in the area carries a sourced figure')
  line()
  line('| Budget area | Decisions | Alternatives | That move the balance | Area appropriation | Status |')
  line('| --- | ---: | ---: | ---: | ---: | --- |')
  for (const row of rows) {
    const appropriation = row.areaAppropriation === null ? 'not verified' : dollars(row.areaAppropriation)
    line(
      `| ${row.name} | ${row.decisions} | ${row.alternatives} | ${row.scoredAlternatives} | ${appropriation} | ${row.status} |`,
    )
  }
  line()

  const placeholders = rows.filter((r) => r.status === 'placeholder')
  const partials = rows.filter((r) => r.status === 'partial')

  line('## Areas still lacking meaningful choices')
  line()
  if (placeholders.length === 0 && partials.length === 0) {
    line('None. Every budget area offers at least one alternative that moves the balance.')
  } else {
    if (placeholders.length > 0) {
      line('**No sourced alternative at all:**')
      line()
      for (const row of placeholders) {
        line(`- ${row.name} — ${row.decisions} decisions, ${row.alternatives} alternatives, none scored`)
      }
      line()
    }
    if (partials.length > 0) {
      line('**Partially populated:**')
      line()
      for (const row of partials) {
        line(
          `- ${row.name} — ${row.scoredAlternatives} of ${row.alternatives} alternatives carry a sourced figure`,
        )
      }
      line()
    }
  }

  line('## Options by provenance')
  line()
  line('Whether the arithmetic is traceable and whether anyone proposed the policy are two')
  line('different questions. This table answers the second.')
  line()
  line('| Provenance | Options | Meaning |')
  line('| --- | ---: | --- |')
  line(`| Enacted policy | ${provenance.enacted ?? 0} | What S.L. 2026-41 actually does. |`)
  line(
    `| Documented alternative | ${provenance.documented ?? 0} | The dollar impact equals an amount an official document states. |`,
  )
  line(
    `| Published proposal | ${provenance.proposal ?? 0} | Published in an official document with a fiscal estimate behind it. |`,
  )
  line(
    `| Illustrative allocation scenario | ${provenance.illustrative ?? 0} | Constructed for this exercise. Not proposed by any North Carolina official or institution. See REPLACEMENT_INVENTORY.md. |`,
  )
  line()

  line('## Options by arithmetic status')
  line()
  line('| Status | Counted in the balance | Options |')
  line('| --- | --- | ---: |')
  line(`| verified | yes | ${counts.verified ?? 0} |`)
  line(`| derived | yes | ${counts.derived ?? 0} |`)
  line(`| pending | no | ${counts.pending ?? 0} |`)
  line(`| illustrative | no | ${counts.illustrative ?? 0} |`)
  line()

  line('## Decisions still awaiting a figure')
  line()
  const awaiting = DATASET.decisions.filter(
    (d) => !d.choices.some((c) => !c.isEnactedBaseline && isScored(c) && choiceBalanceEffect(c) !== 0),
  )
  if (awaiting.length === 0) {
    line('None.')
  } else {
    line(`${awaiting.length} of ${DATASET.decisions.length} decisions offer no alternative that moves the balance.`)
    line()
    for (const decision of awaiting) {
      const category = CATEGORIES.find((c) => c.id === decision.category)
      line(`- \`${decision.id}\` — ${decision.title} (${category?.name})`)
    }
  }
  line()

  if (errors.length > 0) {
    line('## Validation errors')
    line()
    for (const error of errors) {
      line(`- **${error.where}** — ${error.message}`)
    }
    line()
  }

  return out.join('\n')
}

console.log(report())
