/**
 * The replacement inventory.
 *
 * Every illustrative allocation scenario in the dataset, with the official
 * proposal or fiscal estimate that would replace it. Generated from the data,
 * so it cannot drift out of step with what the application actually shows.
 *
 * Run with:  npm run report:replacements
 * Write it:  npx vite-node src/tools/replacementInventory.ts > REPLACEMENT_INVENTORY.md
 */
import { DATASET } from '../data'
import { CATEGORIES } from '../data/categories'
import { illustrativeOptions, provenanceSummary } from '../data/validate'
import { choiceBalanceEffect } from '../engine/budget'

const dollars = (n: number): string =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(n)

const categoryName = (id: string): string =>
  CATEGORIES.find((c) => c.id === id)?.name ?? id

/**
 * Group by the document that would replace them, so the inventory doubles as a
 * shopping list: obtaining one document clears a whole block at once.
 */
function groupByNeed(): Map<string, Array<{ decision: string; option: string }>> {
  const groups = new Map<string, Array<{ decision: string; option: string }>>()
  for (const { decision, choice } of illustrativeOptions(DATASET)) {
    const need = choice.replacementNeeded ?? '(not stated)'
    if (!groups.has(need)) groups.set(need, [])
    groups.get(need)!.push({ decision: decision.id, option: choice.id })
  }
  return groups
}

function report(): string {
  const rows = illustrativeOptions(DATASET)
  const counts = provenanceSummary(DATASET)
  const out: string[] = []
  const line = (s = '') => out.push(s)

  line('# Replacement inventory')
  line()
  line('Generated by `npm run report:replacements`. Do not edit by hand.')
  line()
  line(
    'Every **illustrative allocation scenario** in the dataset, and the official proposal or',
  )
  line(
    'fiscal estimate that would replace it with a documented alternative. An illustrative',
  )
  line(
    'scenario has exact arithmetic on a sourced figure, but the change itself was constructed',
  )
  line(
    'for this exercise: **no North Carolina official or institution proposed it**, and it must',
  )
  line('never be described as a policy proposal.')
  line()
  line(`- **Dataset version:** ${DATASET.version}`)
  line(`- **Illustrative options to replace:** ${rows.length}`)
  line(`- **Options already documented:** ${(counts.enacted ?? 0) + (counts.documented ?? 0)}`)
  line(`- **Published proposals in the dataset:** ${counts.proposal ?? 0}`)
  line()

  line('## What would clear the most at once')
  line()
  line('Grouped by the document needed, most impactful first.')
  line()
  const groups = [...groupByNeed().entries()].sort((a, b) => b[1].length - a[1].length)
  for (const [need, items] of groups) {
    line(`### ${items.length} option${items.length === 1 ? '' : 's'}`)
    line()
    line(`**Needed:** ${need}`)
    line()
    line('Clears: ' + items.map((i) => `\`${i.decision}/${i.option}\``).join(', '))
    line()
  }

  line('## Every illustrative option')
  line()
  line('| # | Budget area | Decision | Option | Effect on balance | Replaced by |')
  line('| ---: | --- | --- | --- | ---: | --- |')
  rows.forEach(({ decision, choice }, i) => {
    const effect = choiceBalanceEffect(choice)
    line(
      `| ${i + 1} | ${categoryName(decision.category)} | \`${decision.id}\` — ${decision.title} | ` +
        `\`${choice.id}\` — ${choice.label} | ${effect >= 0 ? '+' : ''}${dollars(effect)} | ` +
        `${choice.replacementNeeded ?? '(not stated)'} |`,
    )
  })
  line()

  line('## What each one would run into in practice')
  line()
  line(
    'Recorded so that no illustrative option is read as something that could be carried out',
  )
  line('uniformly as written.')
  line()
  for (const { decision, choice } of rows) {
    line(`- **\`${decision.id}/${choice.id}\`** — ${choice.implementationNote ?? '(not stated)'}`)
  }
  line()

  return out.join('\n')
}

console.log(report())
